"""
Django settings for geo_edu_brazil project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url


def _parse_csv_env(value: str) -> list[str]:
    return [s.strip() for s in value.split(',') if s.strip()]


def _as_bool_default(value: bool) -> bool:
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-+rmzjmu$m&n(2_h8tku!ze5spjb34l5d%a$zhg68jw@p9u-rnh')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango
    
    # Third party apps
    'rest_framework',
    'rest_framework_gis',
    'corsheaders',
    
    # Local apps
    'brasil_edu',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'brasil_edu.middleware.FrontendOriginGateMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geo_edu_brazil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geo_edu_brazil.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Priority: DATABASE_URL > individual env vars > local defaults
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production: Use DATABASE_URL (from Azure Container App or .env)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            engine='django.contrib.gis.db.backends.postgis'
        )
    }
else:
    # Local development: Use individual env vars with sensible defaults
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': config('DB_NAME', default='geo_edu_brazil'),
            'USER': config('DB_USER', default=os.getenv('USER', 'postgres')),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

# Alternative: SpatiaLite (SQLite with spatial extensions) for simple development
# Uncomment if you prefer SQLite for local development
# if not DATABASE_URL:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.contrib.gis.db.backends.spatialite',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GeoDjango specific settings
GDAL_LIBRARY_PATH = config('GDAL_LIBRARY_PATH', default=None)
GEOS_LIBRARY_PATH = config('GEOS_LIBRARY_PATH', default=None)

# Django REST Framework settings
DEFAULT_RENDERERS = ['rest_framework.renderers.JSONRenderer']
if DEBUG:
    DEFAULT_RENDERERS.append('rest_framework.renderers.BrowsableAPIRenderer')

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERERS,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('API_THROTTLE_ANON_RATE', default='120/min'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Cache settings
CACHE_BACKEND = config('DJANGO_CACHE_BACKEND', default='locmem').strip().lower()
REDIS_URL = config('REDIS_URL', default='').strip()
CACHE_DEFAULT_TIMEOUT = config(
    'DJANGO_CACHE_DEFAULT_TIMEOUT_SECONDS',
    default=15 * 60,
    cast=int,
)
CACHE_KEY_PREFIX = config('DJANGO_CACHE_KEY_PREFIX', default='edu_brazil')

if CACHE_BACKEND == 'redis' and REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'KEY_PREFIX': CACHE_KEY_PREFIX,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 200,
                    'retry_on_timeout': True,
                },
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'edu-brazil-local-cache',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'KEY_PREFIX': CACHE_KEY_PREFIX,
        }
    }

# CORS settings (for API access)
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)

DEFAULT_FRONTEND_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://escolanolugarcerto.iadb.org',
    'https://stedubrazilwebprod559v8j.z20.web.core.windows.net',
]

DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://escolanolugarcerto.iadb.org',
    'https://stedubrazilwebprod559v8j.z20.web.core.windows.net',
    (
        'https://aca-backend-edubrazilweb-prod.wonderfulpond-07f886cb.eastus2'
        '.azurecontainerapps.io'
    ),
]

# Only use CORS_ALLOWED_ORIGINS if not allowing all
if not CORS_ALLOW_ALL_ORIGINS:
    cors_origins = config('CORS_ALLOWED_ORIGINS', default='')
    configured_cors_origins = _parse_csv_env(cors_origins)

    # Accept "*" in env as an explicit all-origins override.
    if '*' in configured_cors_origins:
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        CORS_ALLOWED_ORIGINS = sorted(
            set(DEFAULT_FRONTEND_ORIGINS + configured_cors_origins)
        )
else:
    CORS_ALLOWED_ORIGINS = sorted(set(DEFAULT_FRONTEND_ORIGINS))

# CSRF settings (required for production)
csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='')
configured_csrf_origins = _parse_csv_env(csrf_origins)
CSRF_TRUSTED_ORIGINS = sorted(
    set(DEFAULT_CSRF_TRUSTED_ORIGINS + configured_csrf_origins)
)

# Best-effort API access gate for browser traffic.
# NOTE: This helps reduce casual abuse but is not a replacement for proper auth.
api_gate_origins = config('API_FRONTEND_ONLY_ALLOWED_ORIGINS', default='')
configured_api_gate_origins = _parse_csv_env(api_gate_origins)
API_FRONTEND_ONLY_ALLOWED_ORIGINS = sorted(
    set((configured_api_gate_origins or CORS_ALLOWED_ORIGINS) + DEFAULT_FRONTEND_ORIGINS)
)
API_FRONTEND_ONLY_ENFORCED = config(
    'API_FRONTEND_ONLY_ENFORCED',
    default=_as_bool_default(not DEBUG),
    cast=bool,
)
api_path_prefixes = config('API_FRONTEND_ONLY_PATH_PREFIXES', default='/api/')
API_FRONTEND_ONLY_PATH_PREFIXES = tuple(_parse_csv_env(api_path_prefixes) or ['/api/'])
