# Generated by Django 5.2.7 on 2025-10-17 08:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Municipality Name')),
                ('code_ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='IBGE Code')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geographic Boundaries')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geographic Center')),
                ('area_km2', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Area (km²)')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Total Population')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='State Code')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
                ('abbrev', models.CharField(blank=True, max_length=10, verbose_name='Abbreviation')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('total_municipalities', models.IntegerField(default=0, verbose_name='Total Municipalities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hexagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_index', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='H3 Index')),
                ('resolution', models.IntegerField(verbose_name='H3 Resolution')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Hexagon Polygon')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Hexagon Center')),
                ('area_km2', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Hexagon Area (km²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hexagons', to='brasil_edu.municipality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hexagons', to='brasil_edu.state')),
            ],
            options={
                'verbose_name': 'Hexagon',
                'verbose_name_plural': 'Hexagons',
                'db_table': 'hexagons',
                'ordering': ['h3_index'],
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='brasil_edu.state'),
        ),
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_inf_cre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Population 3 months - 3 years')),
                ('pop_inf_pre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Population 4-5 years')),
                ('pop_fund_ai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Population 6-10 years')),
                ('pop_fund_af', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Population 11-14 years')),
                ('pop_med', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Population 15-17 years')),
                ('qt_mat_inf_cre', models.IntegerField(default=0, verbose_name='Creche Enrollment')),
                ('qt_mat_inf_pre', models.IntegerField(default=0, verbose_name='Pre-school Enrollment')),
                ('qt_mat_fund_ai', models.IntegerField(default=0, verbose_name='Elementary 1-5 Enrollment')),
                ('qt_mat_fund_af', models.IntegerField(default=0, verbose_name='Elementary 6-9 Enrollment')),
                ('qt_mat_med', models.IntegerField(default=0, verbose_name='High School Enrollment')),
                ('qt_mat_inf_cre_int', models.IntegerField(default=0, verbose_name='Creche Full-time')),
                ('qt_mat_inf_pre_int', models.IntegerField(default=0, verbose_name='Pre-school Full-time')),
                ('qt_mat_fund_ai_int', models.IntegerField(default=0, verbose_name='Elementary 1-5 Full-time')),
                ('qt_mat_fund_af_int', models.IntegerField(default=0, verbose_name='Elementary 6-9 Full-time')),
                ('qt_mat_med_int', models.IntegerField(default=0, verbose_name='High School Full-time')),
                ('qt_mat_inf_cre_prop', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Creche Enrollment Proportion')),
                ('qt_mat_inf_pre_prop', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Pre-school Enrollment Proportion')),
                ('qt_mat_fund_ai_prop', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Elementary 1-5 Enrollment Proportion')),
                ('qt_mat_fund_af_prop', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Elementary 6-9 Enrollment Proportion')),
                ('qt_mat_med_prop', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='High School Enrollment Proportion')),
                ('qt_mat_bas_n', models.IntegerField(default=0, verbose_name='Night Shift Students')),
                ('qt_salas_utilizadas', models.IntegerField(default=0, verbose_name='Used Classrooms')),
                ('private_qt_mat_inf_cre', models.IntegerField(default=0, verbose_name='Private Creche Enrollment')),
                ('private_qt_mat_inf_pre', models.IntegerField(default=0, verbose_name='Private Pre-school Enrollment')),
                ('private_qt_mat_fund_ai', models.IntegerField(default=0, verbose_name='Private Elementary 1-5 Enrollment')),
                ('private_qt_mat_fund_af', models.IntegerField(default=0, verbose_name='Private Elementary 6-9 Enrollment')),
                ('private_qt_mat_med', models.IntegerField(default=0, verbose_name='Private High School Enrollment')),
                ('data_year', models.IntegerField(default=2024, verbose_name='Data Year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hexagon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_data', to='brasil_edu.hexagon')),
            ],
            options={
                'verbose_name': 'Education Data',
                'verbose_name_plural': 'Education Data',
                'db_table': 'education_data',
                'indexes': [models.Index(fields=['data_year'], name='education_d_data_ye_867061_idx')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_school', models.CharField(max_length=20, unique=True, verbose_name='School Code')),
                ('name_school', models.CharField(max_length=300, verbose_name='School Name')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='School Location')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('urban', models.BooleanField(default=True, verbose_name='Urban Location')),
                ('admin_category', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'State'), ('MUNICIPAL', 'Municipal'), ('PRIVADA', 'Private')], max_length=50, verbose_name='Administrative Category')),
                ('tp_dependencia', models.IntegerField(blank=True, null=True, verbose_name='Administrative Dependency')),
                ('size', models.CharField(blank=True, choices=[('PEQUENO', 'Small'), ('MEDIO', 'Medium'), ('GRANDE', 'Large')], max_length=20, verbose_name='School Size')),
                ('qt_salas_utilizadas', models.IntegerField(default=0, verbose_name='Used Classrooms')),
                ('qt_salas_utilizadas_dentro', models.IntegerField(default=0, verbose_name='Indoor Classrooms')),
                ('qt_salas_utilizadas_fora', models.IntegerField(default=0, verbose_name='Outdoor Classrooms')),
                ('qt_mat_inf_cre', models.IntegerField(default=0, verbose_name='Creche Enrollment')),
                ('qt_mat_inf_pre', models.IntegerField(default=0, verbose_name='Pre-school Enrollment')),
                ('qt_mat_fund_ai', models.IntegerField(default=0, verbose_name='Elementary 1-5 Enrollment')),
                ('qt_mat_fund_af', models.IntegerField(default=0, verbose_name='Elementary 6-9 Enrollment')),
                ('qt_mat_med', models.IntegerField(default=0, verbose_name='High School Enrollment')),
                ('qt_doc_bas', models.IntegerField(default=0, verbose_name='Basic Education Teachers')),
                ('qt_tur_bas', models.IntegerField(default=0, verbose_name='Basic Education Classes')),
                ('ratio_mat_doc_bas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Students per Teacher Ratio')),
                ('ratio_mat_salas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Students per Classroom Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hexagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='brasil_edu.hexagon')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='brasil_edu.municipality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='brasil_edu.state')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name_school'],
                'indexes': [models.Index(fields=['code_school'], name='schools_code_sc_eb6d69_idx'), models.Index(fields=['admin_category'], name='schools_admin_c_59e98d_idx'), models.Index(fields=['municipality'], name='schools_municip_8cdf22_idx'), models.Index(fields=['hexagon'], name='schools_hexagon_8f2857_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['state'], name='municipalit_state_i_a39ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['code_ibge'], name='municipalit_code_ib_fc1d58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='hexagon',
            index=models.Index(fields=['h3_index'], name='hexagons_h3_inde_09dda0_idx'),
        ),
        migrations.AddIndex(
            model_name='hexagon',
            index=models.Index(fields=['resolution'], name='hexagons_resolut_5b86cf_idx'),
        ),
        migrations.AddIndex(
            model_name='hexagon',
            index=models.Index(fields=['state'], name='hexagons_state_i_fecd37_idx'),
        ),
        migrations.AddIndex(
            model_name='hexagon',
            index=models.Index(fields=['municipality'], name='hexagons_municip_af7e66_idx'),
        ),
    ]
