# Generated by Django 5.2.7 on 2025-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasil_edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code_region',
            field=models.CharField(blank=True, max_length=2, verbose_name='Region Code'),
        ),
    ]
